### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by datajerk** [bug400/pyilper#2]
OSX 10.11.6
python35 py35-pyqt4 py35-serial
`python3 setup.py install --user`

```
Traceback (most recent call last):
  File "/Users/egan/Library/Python/3.5/bin/pyilper", line 11, in <module>
    load_entry_point('pyilper==1.4.0b2', 'gui_scripts', 'pyilper')()
  File "/Users/egan/Library/Python/3.5/lib/python/site-packages/pyilper-1.4.0b2-py3.5.egg/pyilper/pyilpermain.py", line 535, in main
    pyilper= cls_pyilper(args)
  File "/Users/egan/Library/Python/3.5/lib/python/site-packages/pyilper-1.4.0b2-py3.5.egg/pyilper/pyilpermain.py", line 232, in __init__
    self.registerTab(TAB_CLASSES[t[0]],t[1])
TypeError: 'int' object is not subscriptable
```

**Comment by bug400** [comment]
Could you please attach your pyilper2d config file? It is in $HOME/Library/Application Support/pyilper.
Thank you.

**Comment by datajerk** [comment]
```
{
   "Drive1_active": true,
   "Drive1_charset": 0,
   "Drive1_drivetype": 2,
   "Drive1_filename": "path_to/HDRIVE1-KEYBOARD.LIF",
   "Drive2_active": false,
   "Drive2_charset": 0,
   "Drive2_drivetype": 2,
   "Drive2_filename": "path_to/PILIMAGE.DAT",
   "Printer1_active": false,
   "Printer1_charset": 0,
   "Printer1_logging": false,
   "Scope_active": false,
   "Scope_logging": false,
   "Scope_logmode": 0,
   "Scope_showidy": false,
   "Terminal_active": true,
   "Terminal_charset": 0,
   "pyilper_active_tab": 4,
   "pyilper_colorscheme": "white",
   "pyilper_idyframe": true,
   "pyilper_mode": 0,
   "pyilper_port": 60001,
   "pyilper_position": [
      1444,
      166
   ],
   "pyilper_remotehost": "localhost",
   "pyilper_remoteport": 60000,
   "pyilper_scrollupbuffersize": 1000,
   "pyilper_tabconfig": [
      1,
      2,
      1,
      1
   ],
   "pyilper_tabconfigchanged": false,
   "pyilper_terminalcharsize": 15,
   "pyilper_terminalsize": "80x40",
   "pyilper_tty": "/dev/tty.usbserial-FTE03NXR",
   "pyilper_ttyspeed": 230400,
   "pyilper_workdir": "path_to"
}
```

**Comment by bug400** [comment]
Unfortunately there is an incompatibility of the config files of pyILPER 1.3.5 development and 1.4.0. Please purge the configuration file pyilper2d or carefully remove the pyilper_tabconfig entry (6 lines). I apologize the trouble caused.

**Comment by bug400** [comment]
Closed, did only affect development version.
